# Server-side of a DNS-over-HTTPS proxy that is behind an HTTP reverse proxy.
# The X-Forwarded-For header provided by any trusted-proxy in 192.168.1.0/24
# will be used to determine the client address.

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"

[listeners.local-doh-behind-proxy]
address = ":443"
protocol = "doh"
resolver = "cloudflare-dot"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
frontend = { trusted-proxy = "192.168.1.0/24" }
